//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusNotifier {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ConfigSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigSettings defaultInstance = ((ConfigSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigSettings())));
        
        public static ConfigSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3057")]
        public string StopNumber {
            get {
                return ((string)(this["StopNumber"]));
            }
            set {
                this["StopNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string RouteNumber {
            get {
                return ((string)(this["RouteNumber"]));
            }
            set {
                this["RouteNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("492")]
        public string RouteUniqueIdentifier {
            get {
                return ((string)(this["RouteUniqueIdentifier"]));
            }
            set {
                this["RouteUniqueIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAlerts {
            get {
                return ((bool)(this["EnableAlerts"]));
            }
            set {
                this["EnableAlerts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public uint AlertStart {
            get {
                return ((uint)(this["AlertStart"]));
            }
            set {
                this["AlertStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public uint AlertEnd {
            get {
                return ((uint)(this["AlertEnd"]));
            }
            set {
                this["AlertEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint AlertWhenETA {
            get {
                return ((uint)(this["AlertWhenETA"]));
            }
            set {
                this["AlertWhenETA"] = value;
            }
        }
    }
}
